"""add is_unanswered to conv_messages

Revision ID: c0fc0a5ef488
Revises: cad864d39efe
Create Date: 2026-05-24 23:43:03.897273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fc0a5ef488'
down_revision: Union[str, None] = 'cad864d39efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conv_messages', sa.Column('is_unanswered', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conv_messages', 'is_unanswered')
    # ### end Alembic commands ###
